name: MyPy check

on:
  push:
    branches: [ master, "feature/*", "bugfix/*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jpetrucciani/mypy-check@0.971
      with:
        path: certomancer
        requirements: "types-PyYAML types-python-dateutil types-tzlocal"
        requirements_file: "requirements.txt"
